<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLN904jV\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLN904jV/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLN904jV.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLN904jV\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLN904jV\App_KernelProdContainer([
    'container.build_hash' => 'LN904jV',
    'container.build_id' => '91321a99',
    'container.build_time' => 1590520335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLN904jV');
