<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], []],
    'admin_categories' => [[], ['_controller' => 'App\\Controller\\AdminCategoriesController::index'], [], [['text', '/admin/categories']], [], []],
    'admin_content' => [[], ['_controller' => 'App\\Controller\\AdminContentController::index'], [], [['text', '/admin/content']], [], []],
    'admin_order' => [[], ['_controller' => 'App\\Controller\\AdminOrderController::index'], [], [['text', '/admin/order']], [], []],
    'approve' => [['id'], ['_controller' => 'App\\Controller\\AdminOrderController::approve'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/approve']], [], []],
    'cancel' => [['id'], ['_controller' => 'App\\Controller\\AdminOrderController::cancel'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/cancel']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminProductController::index'], [], [['text', '/admin']], [], []],
    'add_new' => [[], ['_controller' => 'App\\Controller\\AdminProductController::insert'], [], [['text', '/admin/insert']], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\AdminProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete']], [], []],
    'edit_product' => [['id'], ['_controller' => 'App\\Controller\\AdminProductController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], []],
    'seller' => [[], ['_controller' => 'App\\Controller\\AdminSellerProductController::index'], [], [['text', '/seller']], [], []],
    'seller_insert' => [[], ['_controller' => 'App\\Controller\\AdminSellerProductController::insert'], [], [['text', '/seller/insert']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\AdminSellerProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/seller/delete']], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\AdminSellerProductController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/seller/edit']], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], []],
    'cart_add' => [['id'], ['_controller' => 'App\\Controller\\CartController::add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/add']], [], []],
    'cart_remove' => [['id'], ['_controller' => 'App\\Controller\\CartController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/remvove']], [], []],
    'categories' => [['title'], ['_controller' => 'App\\Controller\\CategoriesController::index'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/category']], [], []],
    'default' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'order' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'product' => [['slug'], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/product/details']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\SearchController::index'], [], [['text', '/search']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
