<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5AIzgg5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5AIzgg5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5AIzgg5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5AIzgg5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5AIzgg5\App_KernelDevDebugContainer([
    'container.build_hash' => '5AIzgg5',
    'container.build_id' => '02d931f6',
    'container.build_time' => 1590520237,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5AIzgg5');
